apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-toleration-no-label
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: workload-type
            operator: In
            values:
            - compute-optimized
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "cloudforbeginners.com/compute-optimized"
    operator: "Equal"
    value: "true"
    effect: "NoExecute"
